# Generated by Django 2.2.7 on 2021-04-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('email_address', models.TextField(blank=True)),
                ('profile_img_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(auto_now=True, null=True)),
                ('blood_type', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('email_address', models.TextField(blank=True)),
                ('profile_img_url', models.URLField(blank=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='project.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('image_file', models.ImageField(blank=True, upload_to='')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('Oxygen_level', models.TextField(blank=True)),
                ('emotions', models.TextField(blank=True)),
                ('Comments', models.TextField(blank=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Doctor')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Profile')),
            ],
        ),
    ]
