# Generated by Django 2.2.7 on 2021-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210427_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='Comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statusmessage',
            name='Oxygen_level',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statusmessage',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='statusmessage',
            name='emotions',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
    ]
