# Generated by Django 2.2.7 on 2021-04-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210428_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='date',
        ),
    ]
