# Generated by Django 2.2.7 on 2021-04-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_statusmessage_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmessage',
            old_name='Comments',
            new_name='temperature',
        ),
    ]
