# Generated by Django 2.2.7 on 2021-03-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_auto_20210324_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
