# Generated by Django 2.2.7 on 2021-04-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_statusmessage_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='mini_fb.Profile'),
        ),
    ]
